[package]
name = "cli_json_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = { version = "2.10.0", features = ["serde"] }
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
